relativeTimeSince:
.global 	relativeTimeSince

    // TODO: Implement this function in x86 64-bit assembly using the System V AMD64 ABI
    //       See the wiki for the functionality you need to implement
    //       Note: 
    //          * time_t is of the type ssize_t (long int) on x86_64 
    //          * read the IDIV instruction description very carefully if you choose to use it 
    //            (Note the register layout for the input! The notation RDX:RAX defines the 
    //             higher 64 bit of a 128-bit word to be stored in rdx and the lower 64 bit in rax.)
    //          * this layout has further implication if the data ha a negative sign (hint: you may 
    //            need to sign-extend the register, there are instructions for this purpose!)

    ud2 // Remove this when you start your implementation
